# docker-compose.yml
version: '3'

services:
  # list all service (web, server...)
  server:
    # in dev, we use the local image rather than pulling it
    build: ./server
    ports:
      - 5000:5000
    # override the CMD command
    command: npm run start:dev
  mongodb:
    image: mongo
