# docker-compose.dev.yml
version: '3'

services:
  client:
    environment:
      - WDS_SOCKET_PORT=0
    # build local image rater than pulling it
    build: ./client
    # sync port
    ports:
      - 8080:3000
    # link volume
    volumes:
      - ./client/src/:/app/src/
  server:
    build: ./server
    # override CMD command in Dockerfile
    command: npm run dev
    ports:
      - 5000:5000
    volumes:
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
